<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Wydatki_kategorie_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get wydatki_kategorie by id_kat
     */

    function get_wydatki_kategorie($id_kat) {
        return $this->db->get_where('wydatki_kategorie', array('id_kat' => $id_kat))->row_array();
    }

    /*
     * Get all wydatki_kategorie
     */

    function get_all_wydatki_kategorie() {
        $this->db->order_by('id_kat', 'desc');
        return $this->db->get('wydatki_kategorie')->result_array();
    }

    /*
     * function to add new wydatki_kategorie
     */

    function add_wydatki_kategorie($params) {
        $this->db->insert('wydatki_kategorie', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update wydatki_kategorie
     */

    function update_wydatki_kategorie($id_kat, $params) {
        $this->db->where('id_kat', $id_kat);
        return $this->db->update('wydatki_kategorie', $params);
    }

    /*
     * function to delete wydatki_kategorie
     */

    function delete_wydatki_kategorie($id_kat) {
        return $this->db->delete('wydatki_kategorie', array('id_kat' => $id_kat));
    }

}
